version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
before_build:
  - nuget restore

deploy:
- provider: NuGet
  server:
  api_key:
    secure: fGNwXOtebe3kxu5SrB90CrbaCxVxuzuCQh3Ipcc0G/3cutoNZf7d7G6AaQ4fRv2l
  on:
    branch: master